### PR TITLE
Feature correct libnice for use with Python through GObject Introspection

### PR DESCRIPTION
**Pull request by marclabranche**

### CODE REVIEW

**Comment by jasonvasquez** [comment]
Looks like there are some merge conflicts to resolve first.  We should leave this in a branch for a PR back to the upstream project anyway   (we should rename the branch :) )

After that, let's squash commits so we can provide upstream with a singular commit with the change.

**Comment by jasonvasquez** [comment]
Closing for now, as it's really outdated.

**Comment by dsrees** [comment]
@jasonvasquez idk LGTM 😂

**Comment by hwrd** [comment]
:shipit:

**Pull request closed without merging**
